# -*- coding: utf-8 -*-
"""Visualize GVI_Step4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fbv2vbz1Lph8ujCCuqBux7Nj0MUfUew7
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import os

# Set the directory containing your CSV files
directory = '/content/drive/MyDrive/C257 Project/Data/GVI_Output_CSV'

# Initialize a list to hold DataFrames
dfs = []

# Loop through each file in the directory
for filename in os.listdir(directory):
    if filename.endswith('.csv'):
        # Construct full file path
        file_path = os.path.join(directory, filename)
        try:
            # Read the CSV file
            current_data = pd.read_csv(file_path)
            # Add the DataFrame to the list
            dfs.append(current_data)
        except pd.errors.EmptyDataError:
            print(f'Warning: The file {filename} is empty and will be skipped.')

# Concatenate all DataFrames in the list
combined_csv = pd.concat(dfs, ignore_index=True)

# Specify the name of the output file
output_file = 'combined_csv.csv'

# Write the combined DataFrame to a new CSV file
combined_csv.to_csv(os.path.join(directory, output_file), index=False)

print(f'All CSV files have been combined into {output_file}')

import pandas as pd
GVI_fd = pd.read_csv('/content/drive/MyDrive/C257 Project/Data/GVI_Output_CSV/combined_csv.csv', sep=',')

GVI_fd

import folium

# Initialize a map centered at [53, 12] at zoom level 5
m = folium.Map(location=[37.7749, -122.4194], zoom_start=12,)

# Add Stamen Toner tile layer
folium.raster_layers.TileLayer(
    tiles='https://tiles.stadiamaps.com/tiles/stamen_toner_background/{z}/{x}/{y}{r}.png',
    attr='&copy; <a href="https://stadiamaps.com/" target="_blank">Stadia Maps</a> &copy; <a href="https://stamen.com/" target="_blank">Stamen Design</a> &copy; <a href="https://openmaptiles.org/" target="_blank">OpenMapTiles</a> &copy; <a href="https://www.openstreetmap.org/about" target="_blank">OpenStreetMap</a> contributors',
    max_zoom=20,
    name='Stamen Toner',
    overlay=False,
    control=True
).add_to(m)

# Display the map
m

GVI_fd = GVI_fd.dropna(subset=['GreenView'])

import folium
import pandas as pd
from branca.colormap import LinearColormap

# Assuming `data` is your DataFrame
# Make sure that 'GreenView', 'Latitude', and 'Longitude' columns exist in your DataFrame

# Define the color scale
color_scale = LinearColormap(['yellow', 'green','darkgreen'], vmin=GVI_fd['GreenView'].min(), vmax=GVI_fd['GreenView'].max())

# Add points to the map
for idx, row in GVI_fd.iterrows():
    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=0.5,  # Size of the circle marker
        popup=row['PanoID'],  # Popup text
        color=color_scale(row['GreenView']),  # Get color from color_scale
        fill=True
    ).add_to(m)

# Add the color scale to the map for reference
color_scale.add_to(m)

# Display the map
m

